coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 90%
        threshold: 2%

ignore:
  - "tests/**/*"
  - "examples/**/*" 