[package]
name = "cortex-ai"
version = "0.1.0"
edition = "2021"
description = "Flow library for Cortex"
license = "MIT"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
flume = "0.11"

[dev-dependencies]
tokio = { version = "1.0", features = ["full", "test-util"] }
