[package]
name = "cortex-pipeline"
version = "0.1.0"
edition = "2021"
description = "Pipeline library for Cortex"
license = "MIT"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
flume = "0.11"