name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview rustfmt clippy
        
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
        
      - name: Install llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install just
        uses: taiki-e/install-action@just
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build cortex-ai
        run: just build
      
      - name: Run tests
        run: just test-ci

      - name: Run doctests
        run: just test-doc
        
      - name: Check formatting
        run: just fmt
        
      - name: Check linting
        run: just lint
        
      - name: Generate coverage report
        run: just coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./target/llvm-cov-target/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: Publish
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Get build number
        id: build_number
        run: echo "::set-output name=number::${{ github.run_number }}"
        
      - name: Update cortex-ai version
        run: |
          VERSION="0.1.${{ steps.build_number.outputs.number }}"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" cortex-ai/Cargo.toml
          
      - name: Update cortex-sources version
        run: |
          VERSION="0.1.${{ steps.build_number.outputs.number }}"
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" cortex-sources/Cargo.toml
          # Update cortex-ai dependency version
          sed -i "s/cortex-ai = { path = \"..\/cortex-ai\", version = \".*\" }/cortex-ai = { path = \"..\/cortex-ai\", version = \"$VERSION\" }/" cortex-sources/Cargo.toml
        
      - name: Publish cortex-ai
        run: cargo publish -p cortex-ai --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

      # Wait a bit for crates.io to process the cortex-ai publish
      - name: Wait for crates.io
        run: sleep 30

      - name: Publish cortex-sources
        run: cargo publish -p cortex-sources --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}