name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
        
      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest
        
      - name: Install grcov
        uses: taiki-e/install-action@grcov
        
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Run tests
        working-directory: ./cortex-ai
        run: cargo nextest run --profile ci
        
      - name: Check formatting
        working-directory: ./cortex-ai
        run: cargo fmt --all -- --check
        
      - name: Check linting
        working-directory: ./cortex-ai
        run: cargo clippy -- -D warnings
        
      - name: Generate coverage report
        working-directory: ./cortex-ai
        run: |
          grcov . \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            -o lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./cortex-ai/lcov.info
          fail_ci_if_error: true
